### Create Product
POST http://localhost:8000/product/create
Content-Type: application/json

{
  "productName": "Nike airforce ",
  "productImage": [
    "https://cdn.pixabay.com/photo/2016/11/19/18/06/feet-1840619_1280.jpg",
    "https://cdn.pixabay.com/photo/2021/07/09/02/29/shoes-6398150_1280.jpg"
  ],
  "rating": 4.5,
  "price": 13000,
  "discount": "20%",
  "description": "Comfortable and stylish running shoes suitable for daily wear.",
  "gender": "Unisex",
  "colors": [
    "White",
    "#FF5733"
  ],
  "size": [
    "Medium",
    "Large",
    "XL",
    "42"
  ]
}

### Get All Products
GET http://localhost:8000/product/get-all

### Get Specific Product (Replace ID with a real ID from the Get All response)
GET http://localhost:8000/product/get-specific/6933a946db8519f6fc89fec3

### Delete Product (Replace ID with a real ID)
DELETE http://localhost:8000/product/delete/6932dd335414d5d4a1cbf384