###
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
  "userName": "prabin shrestha",
  "email": "xthaprabin125@gmail.com",
  "password": "password123",
  "confirmPassword": "password123"
}

###

GET http://localhost:8000/api/auth/verify-email/206a84b080b7c7c5ba727d8a8085acc1841c6304be403cc5d64301651e07d832



###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "email": "xthaprabin125@gmail.com",
  "password": "password123",
  "confirmPassword": "password123"
}