###
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "prabin shrestha",
  "email": "xthaprabin125@gmail.com",
  "password": "password123"
}

###

GET http://localhost:8000/auth/verify-email/cd16e1ac83c9b4fcbb7a2236476e265aa7fd5f4b14ee7aa1d277e92299b17b66



###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
 "email": "xthaprabin125@gmail.com",
  "password": "password123"
}